version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: jenkins/scripts/deliver.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: jenkins/scripts/test.sh
      timeout: 300
      runas: root
